#!/bin/bash

setup-nerdctl() {
containerd-rootless-setuptool.sh install
containerd-rootless-setuptool.sh install-buildkit
containerd-rootless-setuptool.sh install-fuse-overlayfs
sudo loginctl enable-linger scott
}

get-pulumi (){
curl -fsSL https://get.pulumi.com | sh
}

ecr-login (){
ID=$(aws sts get-caller-identity --query "Account" --no-cli-pager --output text)
aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin $ID.dkr.ecr.ap-southeast-2.amazonaws.com
}

ecr-push (){
IMAGE="$@"
ID=$(aws sts get-caller-identity --query "Account" --no-cli-pager --output text)
docker push $ID.dkr.ecr.ap-southeast-2.amazonaws.com/$IMAGE
}

ecr-pull (){
IMAGE="$@"
ID=$(aws sts get-caller-identity --query "Account" --no-cli-pager --output text)
docker pull $ID.dkr.ecr.ap-southeast-2.amazonaws.com/$IMAGE
}

ecr-tag (){
IMAGE="$@"
ID=$(aws sts get-caller-identity --query "Account" --no-cli-pager --output text)
docker tag $IMAGE:latest $ID.dkr.ecr.ap-southeast-2.amazonaws.com/$IMAGE:latest
}
